export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const UNAUTHORISED_ERROR = 'UNAUTHORISED_ERROR';
export const LOG_OUT = 'LOG_OUT';

export const SET_CLIENT_DETAILS = 'SET_CLIENT_DETAILS';
export const UPDATE_CLIENT_DETAILS = 'UPDATE_CLIENT_DETAILS';
export const UPDATE_CLIENT_LIST = 'UPDATE_CLIENT_LIST';
export const CLIENT_LIST = 'CLIENT_LIST';

export const SET_CLIENT_CLINICAL_DETAILS = 'SET_CLIENT_CLINICAL_DETAILS';
export const CLEAR_CLIENT_CLINICAL_DETAILS = 'SET_CLIENT_CLINICAL_DETAILS';

export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';

export const DATE_FROM = 'DATE_FROM';
export const DATE_TO = 'DATE_TO';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_CHV_DETAILS = 'SET_CHV_DETAILS';
